name: Go Odin SDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Golint
      run: |
        go env GOPATH GOBIN
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        source $HOME/.bash_profile
        go get -u golang.org/x/lint/golint
        $GOBIN/golint ./odin-libraries/go/...

    - name: Get Odin SDK Dependencies
      run: |
        export GOBIN=$GOPATH/bin
        go get -v -d ./odin-libraries/go/odinlib/...
        go build -v ./odin-libraries/go/odinlib/...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Set Up Odin
      run: |
        export ODIN_MONGODB=mongodb://localhost:27017
        sudo make mongodb
        cd odin-engine
        make build
        sudo cp config/odin-config.yml /root
        sudo ./odin-engine -id master-node raft0 & 

    - name: Get Odin SDK Dependencies
      run: |
        export GOBIN=$GOPATH/bin
        go get -v -d ./odin-libraries/go/odinlib/...
    
    - name: Test Odin SDK
      run: |
        export ODIN_EXEC_ENV=True
        export ODIN_MONGODB=mongodb://localhost:27017
        go test -cover ./odin-libraries/go/odinlib/...
