# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Odin SDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.0.0, 12.0.0, 14.0.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set Up Odin
      run: |
        export ODIN_MONGODB=mongodb://localhost:27017
        sudo make mongodb
        cd odin-engine
        make build
        sudo cp config/odin-config.yml /root
        sudo ./odin-engine -id master-node raft0 &

    - name: Install Odin SDK Dependencies
      run: |
        cd odin-libraries/nodejs
        npm install

    - name: Test Odin SDK
      run: |
        export ODIN_MONGODB=mongodb://localhost:27017
        cd odin-libraries/nodejs
        npm run test
